# These are supported funding model platforms
# Uncomment and fill in the platforms you use

github: [MetaCubeX]
# patreon:
# open_collective:
# ko_fi:
# buy_me_a_coffee:
# custom: ['https://your-link.com']
