parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

env:
  node: true

plugins:
  - '@typescript-eslint'
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier

settings:
  import/resolver:
    typescript:
    node: true

rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'

  no-empty: off

  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev: '*'
      next: if
    - blankLine: always
      prev: if
      next: '*'
    - blankLine: always
      prev: '*'
      next: switch
    - blankLine: always
      prev: switch
      next: '*'
