export enum AccessorKey {
  Close = 'Close',
  ID = 'ID',
  Type = 'Type',
  Process = 'Process',
  Host = 'Host',
  Rule = 'Rule',
  Chains = 'Chains',
  DlSpeed = 'DL Speed',
  ULSpeed = 'UL Speed',
  Download = 'DL',
  Upload = 'UL',
  Source = 'Source',
  Destination = 'Destination',
}
